language: node_js
node_js:
 - 8

jobs:
 include:
  - stage: test
    script:
     - npm test
  - stage: upload
    script:
     - npm run build
     - node deploy.js
    if: type = push AND branch = master
